# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
# ...


    App\EventListener\DynamicDatabaseConnectorEventListener:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $connection: '@doctrine.dbal.default_connection'
            $security: '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }